spring:
  datasource:
    url: "jdbc:h2:mem:wd;DATABASE_TO_UPPER=true"
    username: "sa"
    password: "pswd"
    driver-class-name: "org.h2.Driver"
  sql:
    init:
      mode: embedded
  jpa:
    hibernate:
      naming:
        physical-strategy: "org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"

exchange-service:
  nbp:
    usd: "https://api.nbp.pl/api/exchangerates/rates/c/usd/today"
